"""Add stock_status to Class

Revision ID: 09bcc30ea9e4
Revises: 7e10841bd8cf
Create Date: 2024-05-21 21:20:32.747734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09bcc30ea9e4'
down_revision = '7e10841bd8cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_status', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('stock_status')

    # ### end Alembic commands ###
