version: "3"

networks:
  staff_net_int:
    internal: true
  staff_net_ext:
    internal: false

volumes:
  db:

services:
  frontend:
    image: nginx:latest
    working_dir: "/usr/share/nginx/html"
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    networks:
      - staff_net_int
    expose:
      - 80
    tty: true
    restart: always
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: "/backend"
    environment:
      - TZ=Asia/Tokyo
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/staff
    networks:
      - staff_net_int
    expose:
      - 5001
    volumes:
      - ./backend:/backend:ro
    command: flask run --host=0.0.0.0 --port=5001
    tty: true
    restart: always

  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=staff
      - TZ=Asia/Tokyo
    networks:
      - staff_net_int
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
    tty: true
    restart: always

  tunnel:
    image: cloudflare/cloudflared:latest
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
    networks:
      - staff_net_int
      - staff_net_ext
    command: tunnel run
    tty: true
    restart: always
